name: trade_chart
description: Trade Chart is specifically used by PT. Mirae Asset Sekuritas Indonesia.
version: 0.1.11
homepage: https://github.com/appsworkspace/trade_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
